Modify the git pre-commit hook to check if license headers were added instead of adding them
## Why

In the current implementation of the git pre-commit hook, it runs `mvn validate license:format` which would automatically add license headers to relevant files that do not have them. If it passes successfully (and adds missing license headers) the commit would complete after the user types in a commit message, but wouldn't include the new changes from the license header additions. This could cause the user to incorrectly assume that the pre-commit hook had already added the necessary license headers and go on their merry way, though technically the user's PR build will fail since license headers are checked when `mvn verify` is called so they will be notified anyway, but only after waiting for their PR build to fail.

## What

Modify the pre-commit hook to _check_ (via `mvn validate license:check`) that all appropriate license headers have been added to new files instead of actually adding them (via `mvn validate license:format`)
Also execute `mvn git-build-hook:install` during the `validate` phase to ensure the latest pre-commit hook is updated in `.git/hooks`

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -19,10 +19,15 @@ command_exists mvn || {
 	exit 1
 }
 
-echo "Updating license headers where necessary..."
-if mvn --quiet validate license:format; then
-	echo "Successfully updated license headers"
+echo "Checking license headers..."
+echo "=================================="
+mvn --quiet validate license:check
+MVN_STATUS=$?
+
+if [ $MVN_STATUS -eq 0 ]; then
+	echo -e "All license headers are in place. \n"
 else
-	echo >&2 "Failed to update license headers, please check the output of 'mvn validate license:format' to see what's wrong and rectify"
+  echo "=================================="
+	echo -e >&2 "Some license headers are missing. Please run 'mvn validate license:format' to add them. \n"
 	exit 1
 fi
