ci: fix concourse pipeline, pick username from secret

diff --git a/ci/fedramp-promotion-pipeline.yaml b/ci/fedramp-promotion-pipeline.yaml
--- a/ci/fedramp-promotion-pipeline.yaml
+++ b/ci/fedramp-promotion-pipeline.yaml
@@ -26,7 +26,7 @@ resource_types:
     source:
       repository: icr.io/instana-int/int-docker-cogito-instana-local/cogito
       tag: latest
-      username: iamapikey
+      username: ((icr-api-key.username))
       password: ((icr-api-key.password))
 
   - name: slack-notification
@@ -167,7 +167,7 @@ jobs:
             source:
               repository: icr.io/instana-int/int-docker-agent-local/instana-agent-operator/e2e-test-base-image
               tag: main
-              username: iamapikey
+              username: ((icr-api-key.username))
               password: ((icr-api-key.password))
           params:
             ARTIFACTORY_USERNAME_RELEASE: ((delivery-instana-io-release-project-artifact-read-writer-creds.username))
@@ -176,6 +176,10 @@ jobs:
             ARTIFACTORY_CONTAINER_DOCKER_URL: ((delivery-artifactory-docker-agent-release-url))
             ARTIFACTORY_CONTAINER_FEDRAMP_DOCKER_URL: ((delivery-artifactory-docker-agent-fedramp-url))
             ARTIFACTORY_GENERIC_FEDRAMP_URL: ((delivery-artifactory-generic-agent-fedramp-url))
+            ARTIFACTORY_TAAS_USERNAME: ((taas-artifactory-read-writer-creds.username))
+            ARTIFACTORY_TAAS_PASSWORD: ((taas-artifactory-read-writer-creds.password))
+            ICR_PASSWORD: ((icr-api-key.password))
+            ICR_USERNAME: ((icr-api-key.username))
           inputs:
             - name: agent-operator-git-source
             - name: fedramp-version
@@ -186,13 +190,15 @@ jobs:
               - |
                 #!/bin/bash
 
-                RELEASE_ARTIFACTORY_REPOSITORY="${ARTIFACTORY_CONTAINER_DOCKER_URL}/instana-agent-operator"
+                RELEASE_ICR_REPOSITORY="icr.io/instana/instana-agent-operator"
                 FEDRAMP_ARTIFACTORY_REPOSITORY="${ARTIFACTORY_CONTAINER_FEDRAMP_DOCKER_URL}/instana-agent-operator"
+                FEDRAMP_ICR_REPOSITORY="icr.io/instana-rel/rel-docker-agent-fedramp-local/instana-agent-operator"
 
                 DOMAIN=$(echo $ARTIFACTORY_GENERIC_FEDRAMP_URL | cut -d'/' -f1)
                 REPO_PATH=$(echo $ARTIFACTORY_GENERIC_FEDRAMP_URL | cut -d'/' -f2-)
                 FEDRAMP_GENERIC="$DOMAIN/artifactory/$REPO_PATH"
                 FEDRAMP_GENERIC_REPOSITORY="${FEDRAMP_GENERIC}/instana-agent-operator"
+                FEDRAMP_GENERIC_REPOSITORY_TAAS="https://na.artifactory.swg-devops.com/artifactory/instana-team-release-agent-fedramp-generic-local/instana-agent-operator"
 
                 export ARTIFACT_VERSION
                 pushd agent-operator-git-source
@@ -237,7 +243,7 @@ jobs:
                   --src-password ${ARTIFACTORY_PASSWORD_RELEASE} \
                   --dest-username ${ARTIFACTORY_USERNAME_RELEASE} \
                   --dest-password ${ARTIFACTORY_PASSWORD_RELEASE} \
-                  docker://${RELEASE_ARTIFACTORY_REPOSITORY}:${OPERATOR_DOCKER_VERSION} \
+                  docker://${RELEASE_ICR_REPOSITORY}:${OPERATOR_DOCKER_VERSION} \
                   docker://${FEDRAMP_ARTIFACTORY_REPOSITORY}:${COMBINED_VERSION}
                 
                 echo "---> Pushing multi-architectural manifest to ${FEDRAMP_ARTIFACTORY_REPOSITORY} with latest tag"
@@ -246,8 +252,26 @@ jobs:
                   --src-password ${ARTIFACTORY_PASSWORD_RELEASE} \
                   --dest-username ${ARTIFACTORY_USERNAME_RELEASE} \
                   --dest-password ${ARTIFACTORY_PASSWORD_RELEASE} \
-                  docker://${RELEASE_ARTIFACTORY_REPOSITORY}:${OPERATOR_DOCKER_VERSION} \
+                  docker://${RELEASE_ICR_REPOSITORY}:${OPERATOR_DOCKER_VERSION} \
                   docker://${FEDRAMP_ARTIFACTORY_REPOSITORY}:latest
+
+                echo "---> Pushing multi-architectural manifest to ${FEDRAMP_ICR_REPOSITORY}"
+                skopeo copy -a --preserve-digests \
+                  --src-username ${ARTIFACTORY_USERNAME_RELEASE} \
+                  --src-password ${ARTIFACTORY_PASSWORD_RELEASE} \
+                  --dest-username ${ARTIFACTORY_USERNAME_RELEASE} \
+                  --dest-password ${ARTIFACTORY_PASSWORD_RELEASE} \
+                  docker://${RELEASE_ICR_REPOSITORY}:${OPERATOR_DOCKER_VERSION} \
+                  docker://${FEDRAMP_ICR_REPOSITORY}:${COMBINED_VERSION}
+
+                echo "---> Pushing multi-architectural manifest to ${FEDRAMP_ICR_REPOSITORY} with latest tag"
+                skopeo copy -a --preserve-digests \
+                  --src-username ${ARTIFACTORY_USERNAME_RELEASE} \
+                  --src-password ${ARTIFACTORY_PASSWORD_RELEASE} \
+                  --dest-username ${ARTIFACTORY_USERNAME_RELEASE} \
+                  --dest-password ${ARTIFACTORY_PASSWORD_RELEASE} \
+                  docker://${RELEASE_ICR_REPOSITORY}:${OPERATOR_DOCKER_VERSION} \
+                  docker://${FEDRAMP_ICR_REPOSITORY}:latest
                 
                 echo "Pull the released manifest and replace icr.io image with FedRAMP artifactory image"
                 VERSION=${OPERATOR_DOCKER_VERSION} COMBINED_VERSION=${COMBINED_VERSION} ./agent-operator-git-source/ci/scripts/fedramp-manifest-converter.sh
@@ -272,6 +296,23 @@ jobs:
 
                 echo "---> Pushing operator YAML to ${FEDRAMP_GENERIC_REPOSITORY} with latest"
                 status_code=$(curl --silent --output /dev/stderr --write-out "%{http_code}" -u "${ARTIFACTORY_USERNAME_RELEASE}:${ARTIFACTORY_PASSWORD_RELEASE}" -X PUT "https://$FEDRAMP_GENERIC_REPOSITORY/latest/instana-agent-operator.yaml" -T "${MANIFEST_FILE_FEDRAMP}")
+                echo # curl doesn't output a line break on error
+                if test "$status_code" -ne 201; then
+                  echo -e "[\e[1m\e[91mERROR\e[39m\e[21m] curl returned $status_code, exiting..."
+                  exit 1
+                fi
+
+                echo "---> Pushing operator YAML to ${FEDRAMP_GENERIC_REPOSITORY_TAAS} with $COMBINED_VERSION"
+                status_code=$(curl --silent --output /dev/stderr --write-out "%{http_code}" -u "${ARTIFACTORY_TAAS_USERNAME}:${ARTIFACTORY_TAAS_PASSWORD}" -X PUT "https://$FEDRAMP_GENERIC_REPOSITORY_TAAS/$COMBINED_VERSION/instana-agent-operator.yaml" -T "${MANIFEST_FILE_FEDRAMP}")
+                echo # curl doesn't output a line break on error
+                if test "$status_code" -ne 201; then
+                  echo -e "[\e[1m\e[91mERROR\e[39m\e[21m] curl returned $status_code, exiting..."
+                  exit 1
+                fi
+
+
+                echo "---> Pushing operator YAML to ${FEDRAMP_GENERIC_REPOSITORY_TAAS} with latest"
+                status_code=$(curl --silent --output /dev/stderr --write-out "%{http_code}" -u "${ARTIFACTORY_TAAS_USERNAME}:${ARTIFACTORY_TAAS_PASSWORD}" -X PUT "https://$FEDRAMP_GENERIC_REPOSITORY_TAAS/latest/instana-agent-operator.yaml" -T "${MANIFEST_FILE_FEDRAMP}")
                 echo # curl doesn't output a line break on error
                 if test "$status_code" -ne 201; then
                   echo -e "[\e[1m\e[91mERROR\e[39m\e[21m] curl returned $status_code, exiting..."
