fix pushing of operator manifests (#364)
Signed-off-by: Milica Cvrkota <milica.cvrkota@ibm.com>
Co-authored-by: Milica Cvrkota <milica.cvrkota@ibm.com>

diff --git a/ci/fedramp-promotion-pipeline.yaml b/ci/fedramp-promotion-pipeline.yaml
--- a/ci/fedramp-promotion-pipeline.yaml
+++ b/ci/fedramp-promotion-pipeline.yaml
@@ -188,7 +188,12 @@ jobs:
 
                 RELEASE_ARTIFACTORY_REPOSITORY="${ARTIFACTORY_CONTAINER_DOCKER_URL}/instana-agent-operator"
                 FEDRAMP_ARTIFACTORY_REPOSITORY="${ARTIFACTORY_CONTAINER_FEDRAMP_DOCKER_URL}/instana-agent-operator"
-                FEDRAMP_GENERIC_REPOSITORY="${ARTIFACTORY_GENERIC_FEDRAMP_URL}/instana-agent-operator"
+
+                DOMAIN=$(echo $ARTIFACTORY_GENERIC_FEDRAMP_URL | cut -d'/' -f1)
+                REPO_PATH=$(echo $ARTIFACTORY_GENERIC_FEDRAMP_URL | cut -d'/' -f2-)
+                FEDRAMP_GENERIC="$DOMAIN/artifactory/$REPO_PATH"
+                FEDRAMP_GENERIC_REPOSITORY="${FEDRAMP_GENERIC}/instana-agent-operator"
+
                 export ARTIFACT_VERSION
                 pushd agent-operator-git-source
                   source ./ci/scripts/get-latest-fedramp-release-version.sh
@@ -257,9 +262,18 @@ jobs:
                 fi
 
                 echo "---> Pushing operator YAML to ${FEDRAMP_GENERIC_REPOSITORY} with $COMBINED_VERSION"
-                curl -u ${ARTIFACTORY_USERNAME_RELEASE}:${ARTIFACTORY_PASSWORD_RELEASE} \ 
-                      -T $MANIFEST_FILE_FEDRAMP $FEDRAMP_GENERIC_REPOSITORY/$COMBINED_VERSION/instana-agent-operator.yaml
-                
+                status_code=$(curl --silent --output /dev/stderr --write-out "%{http_code}" -u "${ARTIFACTORY_USERNAME_RELEASE}:${ARTIFACTORY_PASSWORD_RELEASE}" -X PUT "https://$FEDRAMP_GENERIC_REPOSITORY/$COMBINED_VERSION/instana-agent-operator.yaml" -T "${MANIFEST_FILE_FEDRAMP}")
+                echo # curl doesn't output a line break on error
+                if test "$status_code" -ne 201; then
+                  echo -e "[\e[1m\e[91mERROR\e[39m\e[21m] curl returned $status_code, exiting..."
+                  exit 1
+                fi
+
+
                 echo "---> Pushing operator YAML to ${FEDRAMP_GENERIC_REPOSITORY} with latest"
-                curl -u ${ARTIFACTORY_USERNAME_RELEASE}:${ARTIFACTORY_PASSWORD_RELEASE} \ 
-                      -T $MANIFEST_FILE_FEDRAMP $FEDRAMP_GENERIC_REPOSITORY/latest/instana-agent-operator.yaml
+                status_code=$(curl --silent --output /dev/stderr --write-out "%{http_code}" -u "${ARTIFACTORY_USERNAME_RELEASE}:${ARTIFACTORY_PASSWORD_RELEASE}" -X PUT "https://$FEDRAMP_GENERIC_REPOSITORY/latest/instana-agent-operator.yaml" -T "${MANIFEST_FILE_FEDRAMP}")
+                echo # curl doesn't output a line break on error
+                if test "$status_code" -ne 201; then
+                  echo -e "[\e[1m\e[91mERROR\e[39m\e[21m] curl returned $status_code, exiting..."
+                  exit 1
+                fi
